# -*- coding: utf-8 -*-
import re
f = open('group_1.txt', 'r')
a = f.read()
f.close()

b=a.split("\n")
result=[]
len_b=len(b)
#print(len(a))
p=0
p2=0
removed=0
for i in b:
    c = i.split(':')
    p+=1
    p2+=1
    if (p==100):
        print(str(p2)+', '+str(round(float(p2)/float(len_b),4)*100)+'%')
        p=0
    if len(c)==2:
        c[0] = re.sub(r'ba','ば',c[0])
        c[0] = re.sub(r'be','べ',c[0])
        c[0] = re.sub(r'bi','び',c[0])
        c[0] = re.sub(r'bo','ぼ',c[0])
        c[0] = re.sub(r'bu','ぶ',c[0])
        
        c[0] = re.sub(r'sha','しゃ',c[0])
        c[0] = re.sub(r'she','しぇ',c[0])
        c[0] = re.sub(r'shi','し',c[0])
        c[0] = re.sub(r'sho','しょ',c[0])
        c[0] = re.sub(r'shu','しゅ',c[0])
        c[0] = re.sub(r'bya','びゃ',c[0])
        c[0] = re.sub(r'bye','びぇ',c[0])
        c[0] = re.sub(r'byi','びぃ',c[0])
        c[0] = re.sub(r'byo','びょ',c[0])
        c[0] = re.sub(r'byu','びゅ',c[0])
        c[0] = re.sub(r'cha','ちぁ',c[0])
        c[0] = re.sub(r'che','ちぇ',c[0])
        c[0] = re.sub(r'chi','ち',c[0])
        c[0] = re.sub(r'cho','ちょ',c[0])
        c[0] = re.sub(r'tyu','ちゅ',c[0])
        c[0] = re.sub(r'da','だ',c[0])
        c[0] = re.sub(r'de','で',c[0])
        c[0] = re.sub(r'dha','でぁ',c[0])
        c[0] = re.sub(r'dhe','でぇ',c[0])
        c[0] = re.sub(r'dhi','でぃ',c[0])
        c[0] = re.sub(r'dho','でょ',c[0])
        c[0] = re.sub(r'dhu','でゅ',c[0])
        c[0] = re.sub(r'di','ぢ',c[0])
        c[0] = re.sub(r'do','ど',c[0])
        c[0] = re.sub(r'du','づ',c[0])
        c[0] = re.sub(r'dya','ぢゃ',c[0])
        c[0] = re.sub(r'dye','ぢぇ',c[0])
        c[0] = re.sub(r'dyi','ぢぃ',c[0])
        c[0] = re.sub(r'dyo','ぢょ',c[0])
        c[0] = re.sub(r'dyu','ぢゅ',c[0])

        c[0] = re.sub(r'fa','ふぁ',c[0])
        c[0] = re.sub(r'fe','ふぇ',c[0])
        c[0] = re.sub(r'fi','ふぃ',c[0])
        c[0] = re.sub(r'fo','ふぉ',c[0])
        c[0] = re.sub(r'fu','ふ',c[0])
        c[0] = re.sub(r'ga','が',c[0])
        c[0] = re.sub(r'ge','げ',c[0])
        c[0] = re.sub(r'gi','ぎ',c[0])
        c[0] = re.sub(r'go','ご',c[0])
        c[0] = re.sub(r'gu','ぐ',c[0])
        c[0] = re.sub(r'gya','ぎゃ',c[0])
        c[0] = re.sub(r'gye','ぎぇ',c[0])
        c[0] = re.sub(r'gyi','ぎぃ',c[0])
        c[0] = re.sub(r'gyo','ぎょ',c[0])
        c[0] = re.sub(r'gyu','ぎゅ',c[0])
        
        c[0] = re.sub(r'hya','ひゃ',c[0])
        c[0] = re.sub(r'hye','ひぇ',c[0])
        c[0] = re.sub(r'hyi','ひぃ',c[0])
        c[0] = re.sub(r'hyo','ひょ',c[0])
        c[0] = re.sub(r'hyu','ひゅ',c[0])
        
        c[0] = re.sub(r'ja','じゃ',c[0])
        c[0] = re.sub(r'je','じぇ',c[0])
        c[0] = re.sub(r'ji','じ',c[0])
        c[0] = re.sub(r'jo','じょ',c[0])
        c[0] = re.sub(r'ju','じゅ',c[0])
        c[0] = re.sub(r'ka','か',c[0])
        c[0] = re.sub(r'ke','け',c[0])
        c[0] = re.sub(r'ki','き',c[0])
        c[0] = re.sub(r'ko','こ',c[0])
        c[0] = re.sub(r'ku','く',c[0])
        c[0] = re.sub(r'kya','きゃ',c[0])
        c[0] = re.sub(r'kye','きぇ',c[0])
        c[0] = re.sub(r'kyi','きぃ',c[0])
        c[0] = re.sub(r'kyo','きょ',c[0])
        c[0] = re.sub(r'kyu','きゅ',c[0])
        c[0] = re.sub(r'la','ぁ',c[0])
        c[0] = re.sub(r'le','ぇ',c[0])
        c[0] = re.sub(r'li','ぃ',c[0])
        c[0] = re.sub(r'lo','ぉ',c[0])
        c[0] = re.sub(r'ltu','っ',c[0])
        c[0] = re.sub(r'q','っ',c[0])
        c[0] = re.sub(r'lu','ぅ',c[0])
        c[0] = re.sub(r'lya','ゃ',c[0])
        c[0] = re.sub(r'lyo','ょ',c[0])
        c[0] = re.sub(r'lyu','ゅ',c[0])
        c[0] = re.sub(r'ma','ま',c[0])
        c[0] = re.sub(r'me','め',c[0])
        c[0] = re.sub(r'mi','み',c[0])
        c[0] = re.sub(r'mo','も',c[0])
        c[0] = re.sub(r'mu','む',c[0])
        c[0] = re.sub(r'mya','みゃ',c[0])
        c[0] = re.sub(r'mye','みぇ',c[0])
        c[0] = re.sub(r'myi','みぃ',c[0])
        c[0] = re.sub(r'myo','みょ',c[0])
        c[0] = re.sub(r'myu','みゅ',c[0])
        c[0] = re.sub(r'nn','ん',c[0])
        c[0] = re.sub(r'na','な',c[0])
        c[0] = re.sub(r'ne','ね',c[0])
        c[0] = re.sub(r'ni','に',c[0])
        
        c[0] = re.sub(r'no','の',c[0])
        c[0] = re.sub(r'nu','ぬ',c[0])
        c[0] = re.sub(r'nya','にゃ',c[0])
        c[0] = re.sub(r'nye','にぇ',c[0])
        c[0] = re.sub(r'nyi','にぃ',c[0])
        c[0] = re.sub(r'nyo','にょ',c[0])
        c[0] = re.sub(r'nyu','にゅ',c[0])
        
        c[0] = re.sub(r'pa','ぱ',c[0])
        c[0] = re.sub(r'pe','ぺ',c[0])
        c[0] = re.sub(r'pi','ぴ',c[0])
        c[0] = re.sub(r'po','ぽ',c[0])
        c[0] = re.sub(r'pu','ぷ',c[0])
        c[0] = re.sub(r'pya','ぴゃ',c[0])
        c[0] = re.sub(r'pye','ぴぇ',c[0])
        c[0] = re.sub(r'pyi','ぴぃ',c[0])
        c[0] = re.sub(r'pyo','ぴょ',c[0])
        c[0] = re.sub(r'pyu','ぴゅ',c[0])
        c[0] = re.sub(r'ra','ら',c[0])
        c[0] = re.sub(r're','れ',c[0])
        c[0] = re.sub(r'ri','り',c[0])
        c[0] = re.sub(r'ro','ろ',c[0])
        c[0] = re.sub(r'ru','る',c[0])
        c[0] = re.sub(r'rya','りゃ',c[0])
        c[0] = re.sub(r'rye','りぇ',c[0])
        c[0] = re.sub(r'ryi','りぃ',c[0])
        c[0] = re.sub(r'ryo','りょ',c[0])
        c[0] = re.sub(r'ryu','りゅ',c[0])
        c[0] = re.sub(r'sa','さ',c[0])
        c[0] = re.sub(r'se','せ',c[0])
        c[0] = re.sub(r'si','し',c[0])
        c[0] = re.sub(r'so','そ',c[0])
        c[0] = re.sub(r'tsu','つ',c[0])
        c[0] = re.sub(r'su','す',c[0])
        c[0] = re.sub(r'ta','た',c[0])
        c[0] = re.sub(r'te','て',c[0])
        c[0] = re.sub(r'tha','てぁ',c[0])
        c[0] = re.sub(r'the','てぇ',c[0])
        c[0] = re.sub(r'thi','てぃ',c[0])
        c[0] = re.sub(r'tho','てょ',c[0])
        c[0] = re.sub(r'thu','てゅ',c[0])
        c[0] = re.sub(r'ti','ち',c[0])
        c[0] = re.sub(r'to','と',c[0])
        c[0] = re.sub(r'tu','つ',c[0])
        c[0] = re.sub(r'tya','ちゃ',c[0])
        c[0] = re.sub(r'tye','ちぇ',c[0])
        c[0] = re.sub(r'tyi','ちぃ',c[0])
        c[0] = re.sub(r'tyo','ちょ',c[0])
        c[0] = re.sub(r'tyu','ちゅ',c[0])
        
        c[0] = re.sub(r'va','う゛ぁ',c[0])
        c[0] = re.sub(r've','う゛ぇ',c[0])
        c[0] = re.sub(r'vi','う゛ぃ',c[0])
        c[0] = re.sub(r'vo','う゛ぉ',c[0])
        c[0] = re.sub(r'vu','う゛',c[0])
        c[0] = re.sub(r'wa','わ',c[0])
        c[0] = re.sub(r'we','うぇ',c[0])
        c[0] = re.sub(r'wi','うぃ',c[0])
        c[0] = re.sub(r'wo','を',c[0])
        c[0] = re.sub(r'wu','う',c[0])
        c[0] = re.sub(r'ha','は',c[0])
        c[0] = re.sub(r'he','へ',c[0])
        c[0] = re.sub(r'hi','ひ',c[0])
        c[0] = re.sub(r'ho','ほ',c[0])
        c[0] = re.sub(r'hu','ふ',c[0])
        c[0] = re.sub(r'ya','や',c[0])
        c[0] = re.sub(r'ye','いぇ',c[0])
        c[0] = re.sub(r'yi','い',c[0])
        c[0] = re.sub(r'yo','よ',c[0])
        c[0] = re.sub(r'yu','ゆ',c[0])
        c[0] = re.sub(r'za','ざ',c[0])
        c[0] = re.sub(r'ze','ぜ',c[0])
        c[0] = re.sub(r'zi','じ',c[0])
        c[0] = re.sub(r'zo','ぞ',c[0])
        c[0] = re.sub(r'zu','ず',c[0])
        c[0] = re.sub(r'zya','じゃ',c[0])
        c[0] = re.sub(r'zye','じぇ',c[0])
        c[0] = re.sub(r'zyi','じぃ',c[0])
        c[0] = re.sub(r'zyo','じょ',c[0])
        c[0] = re.sub(r'zyu','じゅ',c[0])
        c[0] = re.sub(R'a','あ',c[0])
        c[0] = re.sub(r'u','う',c[0])
        c[0] = re.sub(r'e','え',c[0])
        c[0] = re.sub(r'o','お',c[0])
        c[0] = re.sub(r'i','い',c[0])
        m = re.search(r'[a-zA-Z]', c[1])
        #print(c[1], type(m))
        if(m is not None):
            if(len(m.group(0))>=0):
                c1 = re.sub('",','',c[1])
                c2 = c1.split(',')
                c3 = []
                for e in c2:
                    m2 = re.search(r'[a-zA-Z]', e)
                    if(m2 is not None):
                        if(len(m2.group(0))>0):
                            removed += 1
                    else:
                        c3.append(e)
                c[1] = ','.join(c3) + '",'
                if(len(c[1])>2):
                    result.append(c[0]+':'+c[1])
        else:
            result.append(c[0]+':'+c[1])
    else:
        result.append(i)
            
s='\n'.join(result)
print('removed:' + str(removed))
f = open('group_1_new.txt', 'w')
f.write(s)
f.close()
